; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
	adafruit/Adafruit GFX Library@^1.12.3
	olikraus/U8g2@^2.36.14

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps = 
	olikraus/U8g2@^2.36.14
	adafruit/DHT sensor library@^1.4.0
build_flags = -D BOARD_NODEMCU

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = olikraus/U8g2@^2.36.14
build_flags = -D BOARD_MEGA

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = olikraus/U8g2@^2.36.14
build_flags = -D BOARD_ESP32

[env:nano328]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_deps = olikraus/U8g2@^2.36.14
build_flags = -D BOARD_NANO

[env:unor4]
platform = renesas-ra
board = uno_r4_minima
framework = arduino
lib_deps = olikraus/U8g2@^2.36.14
build_flags = -D BOARD_UNOR4

[env:nodemcu1]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_flags = -D NODEMCU1

[env:nodemcu2]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_flags = -D NODEMCU2
